+nowarnTFNPC
+nowarnIWFA
+nowarnSVTL
src/timescale.v
src/ADAP_PRED_REC_SIG_vec_test.v
src/ADAP_PRED_REC_SIG.v
../ADDB/src/ADDB.v
../ADDC/src/ADDC.v
../DELAY/src/DELAY.v
../DELAYPREDIC/src/DELAYPREDIC.v
../FLOATA/src/FLOATA.v
../FLOATB/src/FLOATB.v
../FMULT/src/FMULT.v
../FMULT_ACCUM/src/FMULT_ACCUM.v
../LIMC/src/LIMC.v
../LIMD/src/LIMD.v
../TRIGB/src/TRIGB.v
../UPA1/src/UPA1.v
../UPA2/src/UPA2.v
../UPB/src/UPB.v
../XORA/src/XORA.v

