../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/a1.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/a2.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b1.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b2.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b3.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b4.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b5.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/b6.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/sr1.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/sr2.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq1.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq2.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq3.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq4.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq5.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dq6.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/sez.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/a1.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/a2.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b1.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b2.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b3.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b4.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b5.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/b6.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/sr1.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/sr2.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq1.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq2.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq3.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq4.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq5.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dq6.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/sez.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/a1.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/a2.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b1.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b2.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b3.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b4.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b5.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/b6.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/sr1.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/sr2.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq1.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq2.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq3.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq4.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq5.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dq6.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/sez.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/a1.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/a2.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b1.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b2.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b3.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b4.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b5.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/b6.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/sr1.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/sr2.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq1.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq2.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq3.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq4.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq5.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dq6.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/sez.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/a1.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/a2.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b1.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b2.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b3.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b4.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b5.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/b6.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/sr1.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/sr2.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq1.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq2.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq3.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq4.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq5.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dq6.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/sez.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/a1.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/a2.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b1.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b2.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b3.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b4.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b5.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/b6.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/sr1.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/sr2.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq1.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq2.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq3.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq4.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq5.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dq6.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/sez.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/a1.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/a2.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b1.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b2.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b3.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b4.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b5.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/b6.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/sr1.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/sr2.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq1.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq2.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq3.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq4.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq5.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dq6.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/sez.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/a1.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/a2.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b1.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b2.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b3.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b4.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b5.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/b6.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/sr1.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/sr2.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq1.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq2.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq3.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq4.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq5.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dq6.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/sez.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/se.t
