+nowarnTFNPC
+nowarnIWFA
+nowarnSVTL
src/timescale.v
src/enc_test.v
src/enc.v
../EXPAND/src/EXPAND.v
../SUBTA/src/SUBTA.v
../ADAP_QUAN/src/ADAP_QUAN.v
../I_ADAP_QUAN/src/I_ADAP_QUAN.v
../ADAP_PRED_REC_SIG/src/ADAP_PRED_REC_SIG.v
../QUAN_SCAL_FAC_ADAP/src/QUAN_SCAL_FAC_ADAP.v
../ADAP_SPED_CTL/src/ADAP_SPED_CTL.v
../TON_TRAN_DET/src/TON_TRAN_DET.v
src/IN_REG.v
../CLOCK_GEN/src/CLOCK_GEN.v
../CU/src/CU.v
../RF/src/RF.v
-v /classes/eeee720/maieee/lib/tsmc-0.18/verilog/tsmc18.v
+librescan
