+nowarnTFNPC
+nowarnIWFA
+nowarnSVTL
src/timescale.v
src/ADAP_SPED_CTL_test.v
src/ADAP_SPED_CTL.v
../FUNCTF/src/FUNCTF.v
../FILTA/src/FILTA.v
../DELAY/src/DELAY.v
../FILTB/src/FILTB.v
../SUBTC/src/SUBTC.v
../FILTC/src/FILTC.v
../TRIGA/src/TRIGA.v
../LIMA/src/LIMA.v
