+nowarnTFNPC
+nowarnIWFA
+nowarnSVTL
src/timescale.v
src/mcac_vec_test.v
src/mcac.v
../enc/src/enc.v
../dec/src/dec.v
../enc/src/IN_REG.v
../EXPAND/src/EXPAND.v
../SUBTA/src/SUBTA.v
../I_ADAP_QUAN/src/I_ADAP_QUAN.v
../ADAP_PRED_REC_SIG/src/ADAP_PRED_REC_SIG.v
../DELAYPREDIC/src/DELAYPREDIC.v
../QUAN_SCAL_FAC_ADAP/src/QUAN_SCAL_FAC_ADAP.v
../ADAP_SPED_CTL/src/ADAP_SPED_CTL.v
../TON_TRAN_DET/src/TON_TRAN_DET.v
../ACCUM/src/ACCUM.v
../ADAP_QUAN/src/ADAP_QUAN.v
../ADDA/src/ADDA.v
../ADDB/src/ADDB.v
../ADDC/src/ADDC.v
../ANTILOG/src/ANTILOG.v
../COMPRESS/src/COMPRESS.v
../CU/src/CU.v
../DELAY/src/DELAY.v
../FILTA/src/FILTA.v
../FILTB/src/FILTB.v
../FILTC/src/FILTC.v
../FILTD/src/FILTD.v
../FILTE/src/FILTE.v
../FLOATA/src/FLOATA.v
../FLOATB/src/FLOATB.v
../FMULT/src/FMULT.v
../FMULT_ACCUM/src/FMULT_ACCUM.v
../FUNCTF/src/FUNCTF.v
../FUNCTW/src/FUNCTW.v
../G711/src/G711.v
../IG711/src/IG711.v
../IN_PCM/src/IN_PCM.v
../OUT_PCM/src/OUT_PCM.v
../LIMA/src/LIMA.v
../LIMB/src/LIMB.v
../LIMC/src/LIMC.v
../LIMD/src/LIMD.v
../LOG/src/LOG.v
../MIX/src/MIX.v
../QUAN/src/QUAN.v
../RECONST/src/RECONST.v
../SUBTB/src/SUBTB.v
../SUBTC/src/SUBTC.v
../SYNC/src/SYNC.v
../TONE/src/TONE.v
../TRANS/src/TRANS.v
../TRIGA/src/TRIGA.v
../TRIGB/src/TRIGB.v
../UPA1/src/UPA1.v
../UPA2/src/UPA2.v
../UPB/src/UPB.v
../XORA/src/XORA.v
../CLOCK_GEN/src/CLOCK_GEN.v
../RF/src/RF.v
-v /classes/eeee720/maieee/lib/tsmc-0.18/verilog/tsmc18.v
+librescan
