+nowarnTFNPC
+nowarnIWFA
+nowarnSVTL
src/timescale.v
src/TON_TRAN_DET_vec_test.v
src/TON_TRAN_DET.v
../../mcac/TONE/src/TONE.v
../../mcac/TRIGB/src/TRIGB.v
../../mcac/DELAY/src/DELAY.v
../../mcac/TRANS/src/TRANS.v
