../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/sp.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/16/normal/homing/dx.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/sp.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/24/normal/homing/dx.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/sp.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/32/normal/homing/dx.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/sp.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/se.t
../model/adpcm-itu/vector_out/alaw/dec/40/normal/homing/dx.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/sp.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/16/normal/homing/dx.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/sp.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/24/normal/homing/dx.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/sp.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/32/normal/homing/dx.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/sp.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/se.t
../model/adpcm-itu/vector_out/ulaw/dec/40/normal/homing/dx.t
